### ISSUE TITLE
Request for example code

### ISSUE THREAD

**Issue by mjafartp** [woodemi/libusb.dart#13]
How to get List of Printers and Send Data to printer using this plugin ?

Like Example in [escpospp](https://github.com/Malanche/escpospp)

**Comment by mjafartp** [comment]
How to connect device and send row data ?

**Comment by Sunbreak** [comment]
[quick_usb](https://github.com/woodemi/quick_usb) is implemented on Win/Mac/Linux via [libusb.dart](https://github.com/woodemi/libusb.dart)

Check the example https://github.com/woodemi/quick_usb/blob/master/example/lib/main.dart

**Comment by Sunbreak** [comment]
I'd like to close it if no further info
