### ISSUE TITLE
Example missing on how to use the library?

### ISSUE THREAD

**Issue by jyashi** [woodemi/libusb.dart#23]
Thank you for the package.

Sorry but I cannot see a straightforward way to using it.

1. I cannot see an example section in the packages [https://pub.dev/packages/libusb](url) 
2. I can see an example folder in the github page but the use of it causes errors from listDeviceProducts.dart
 
![image](https://user-images.githubusercontent.com/47436660/162868711-96f780e5-c119-4a28-ba47-0f6f49cc75d4.png)

I just want to import the library on windows platform and use its provided functions to access usb device and send data to it. Will there be a step by step guide in getting this done?

Again thank you for your work and apologies if the solution was obvious but i could not pick up on it.

**Comment by jyashi** [comment]
Thank you. I tried running.. i got the following error.. i need to take extra measures on my PC ?

![image](https://user-images.githubusercontent.com/47436660/162869944-e0a3a840-0838-4a46-a1b9-c51e5dfbb506.png)

**Comment by jyashi** [comment]
Apparently the structs.g.dart file does not exist.

Does it not come included with the quick_usb package?

**Comment by Sunbreak** [comment]
> 2. I can see an example folder in the github page but the use of it causes errors from listDeviceProducts.dart

Does `example/listdevs.list` work?

**Comment by Sunbreak** [comment]
> Thank you. I tried running.. i got the following error.. i need to take extra measures on my PC ?
> 
> ![image](https://user-images.githubusercontent.com/47436660/162869944-e0a3a840-0838-4a46-a1b9-c51e5dfbb506.png)

Something wrong inside `win32` package, which `quick_usb` depends on

> Apparently the structs.g.dart file does not exist.
> 
> Does it not come included with the quick_usb package?

`structs.g.dart` is inside `win32`: https://github.com/timsneath/win32/blob/main/lib/src/structs.g.dart

**Comment by jyashi** [comment]
Okay... adding Win32 to dependencies and `import 'package:win32/win32.dart';` runs the example fine. I will keep digging for the rest and get back here if any problem comes.

**Comment by Sunbreak** [comment]
> * I cannot see an example section in the packages [https://pub.dev/packages/libusb](url)

Fix by https://github.com/woodemi/libusb.dart/commit/9807b5ce0c635153035039eb6c1600db131359a4
